
/** register D will get the value baseaddr + offset for the given segment */
void emitAGetsBasePlusOffset(char *segment, int offset);
void emitDGetsBasePlusOffset(char *segment, int offset);
void emitGetDFromStack();
void emitWriteDToStack();
void emitDecrementSP();
void emitIncrementSP();
void emitPushD();
void emitPopIntoD();
bool emitAdd();
bool emitSub();
bool emitNeg();
bool emitEq();
bool emitGt();
bool emitLt();
bool emitLogicalAnd();
bool emitLogicalOr();
bool emitLogicalNot();
void emitLabel(char *label);
void emitInitLocal();
void emitReturn();
void emitIfGoto(char * label);
void emitGoto(char *label);
void emitPopStatic(int n);
void emitPopLocal(int offset);
void emitPopArgument(int offset);
void emitPopThis(int offset);
void emitPopPointer(int type);
void emitPopThat(int offset);
void emitPopTemp(int offset);
void emitPushStatic(int n);
void emitPushPointer(int type);
void emitPushConstant(int value);
void emitPushThis(int offset);
void emitPushThat(int offset);
void emitPushLocal(int offset);
void emitPushArgument(int offset);
void emitPushTemp(int offset);
void emitBootstrap();
void emitCall(char *functionName, char *moduleName, int nArgs);